// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: servicedef/service.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace CodingMilitia.GrpcSample.Proto.Service {

  /// <summary>Holder for reflection information generated from servicedef/service.proto</summary>
  public static partial class ServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for servicedef/service.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChhzZXJ2aWNlZGVmL3NlcnZpY2UucHJvdG8SCnNlcnZpY2VkZWYaGXNlcnZp",
            "Y2VkZWYvbWVzc2FnZXMucHJvdG8yVQoHQ291bnRlchJKCglJbmNyZW1lbnQS",
            "HC5zZXJ2aWNlZGVmLkluY3JlbWVudFJlcXVlc3QaHS5zZXJ2aWNlZGVmLklu",
            "Y3JlbWVudFJlc3BvbnNlIgBCMloHc2VydmljZaoCJkNvZGluZ01pbGl0aWEu",
            "R3JwY1NhbXBsZS5Qcm90by5TZXJ2aWNlYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::CodingMilitia.GrpcSample.Proto.Messages.MessagesReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
