// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: servicedef/service.proto
#region Designer generated code

using System;
using System.Threading;
using System.Threading.Tasks;
using grpc = global::Grpc.Core;

namespace CodingMilitia.GrpcSample.Proto.Service {
  public static partial class Counter
  {
    static readonly string __ServiceName = "servicedef.Counter";

    static readonly grpc::Marshaller<global::CodingMilitia.GrpcSample.Proto.Messages.IncrementRequest> __Marshaller_IncrementRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::CodingMilitia.GrpcSample.Proto.Messages.IncrementRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::CodingMilitia.GrpcSample.Proto.Messages.IncrementResponse> __Marshaller_IncrementResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::CodingMilitia.GrpcSample.Proto.Messages.IncrementResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::CodingMilitia.GrpcSample.Proto.Messages.IncrementRequest, global::CodingMilitia.GrpcSample.Proto.Messages.IncrementResponse> __Method_Increment = new grpc::Method<global::CodingMilitia.GrpcSample.Proto.Messages.IncrementRequest, global::CodingMilitia.GrpcSample.Proto.Messages.IncrementResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Increment",
        __Marshaller_IncrementRequest,
        __Marshaller_IncrementResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::CodingMilitia.GrpcSample.Proto.Service.ServiceReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of Counter</summary>
    public abstract partial class CounterBase
    {
      public virtual global::System.Threading.Tasks.Task<global::CodingMilitia.GrpcSample.Proto.Messages.IncrementResponse> Increment(global::CodingMilitia.GrpcSample.Proto.Messages.IncrementRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for Counter</summary>
    public partial class CounterClient : grpc::ClientBase<CounterClient>
    {
      /// <summary>Creates a new client for Counter</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public CounterClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for Counter that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public CounterClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected CounterClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected CounterClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::CodingMilitia.GrpcSample.Proto.Messages.IncrementResponse Increment(global::CodingMilitia.GrpcSample.Proto.Messages.IncrementRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return Increment(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::CodingMilitia.GrpcSample.Proto.Messages.IncrementResponse Increment(global::CodingMilitia.GrpcSample.Proto.Messages.IncrementRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Increment, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::CodingMilitia.GrpcSample.Proto.Messages.IncrementResponse> IncrementAsync(global::CodingMilitia.GrpcSample.Proto.Messages.IncrementRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return IncrementAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::CodingMilitia.GrpcSample.Proto.Messages.IncrementResponse> IncrementAsync(global::CodingMilitia.GrpcSample.Proto.Messages.IncrementRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Increment, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override CounterClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new CounterClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(CounterBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Increment, serviceImpl.Increment).Build();
    }

  }
}
#endregion
